Vagrant.configure("2") do |config|

  # Ubuntu VM
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/jammy64"
    ubuntu.vm.box_check_update = false
    ubuntu.vm.hostname = "ubuntu-vm"
    ubuntu.vm.network "private_network", ip: "192.168.56.10"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 3
    end

    ubuntu.vm.boot_timeout = 300 
    ubuntu.vm.synced_folder ".", "/home/vagrant/project"
    
    ubuntu.vm.provision "shell", run: "always", inline: <<-SHELL
      # Update the system
      sudo apt-get update
      sudo apt-get install -y wget apt-transport-https

      # Install the Microsoft GPG key
      wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb

      # Install .NET SDK
      sudo apt-get update
      sudo apt-get install -y dotnet-sdk-8.0

      # Check the installation
      echo "Verify that .NET Core 8 is installed..."
      dotnet --version
      dotnet --list-sdks
      dotnet --list-runtimes

      if command -v dotnet &> /dev/null; then

        # Installing tool
        dotnet nuget add source http://192.168.56.1:5000/v3/index.json --name "BaGet"
        dotnet tool install --global OBashtovyi --version 1.0.0
        
        # Check the installation
        cd /home/vagrant/project
        OBashtovyi version
        OBashtovyi run lab1 -I Lab4/Lab1/INPUT.TXT -o Lab4/Lab1/OUTPUT.TXT
      else
        echo "Cannot start project, .NET Core 8 is not installed!"
      fi
    SHELL
  end


  # Windows VM
  config.vm.define "windows" do |windows|
    windows.vm.box = "gusztavvargadr/windows-10"
    windows.vm.network "private_network", ip: "192.168.56.11"
    windows.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 3
    end

    windows.vm.boot_timeout = 300 
    windows.vm.synced_folder ".", "C:/project"
    
    windows.vm.provision "shell", run: "always", inline: <<-SHELL
      # Install Chocolatey
      if (-not (Get-Command "choco" -ErrorAction SilentlyContinue)) {
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.WebClient]::new().DownloadString('https://chocolatey.org/install.ps1') | Invoke-Expression
      }

      # Install .NET SDK 8.0 and runtime
      choco install dotnet-8.0-sdk -y
      choco install dotnet-8.0-runtime -y

      # Check the installation
      Write-Host "Verifying that .NET Core 8 is installed..."
      dotnet --version
      dotnet --list-sdks
      dotnet --list-runtimes
      
      if (Get-Command "dotnet" -ErrorAction SilentlyContinue) {

        # Installing tool
        dotnet nuget add source http://192.168.56.1:5000/v3/index.json --name "BaGet"
        dotnet tool install --global OBashtovyi --version 1.0.0
        
        OBashtovyi version

        cd C:\\project    

        OBashtovyi run lab1 -I Lab4/Lab1/INPUT.TXT -o Lab4/Lab1/OUTPUT.TXT    

      } else {
        Write-Host ".NET Core 8 installation failed. Manual intervention required."
      }
    SHELL
  end
end


