Vagrant.configure("2") do |config|

  config.vm.define "lab5" do |lab5|
    lab5.vm.box = "ubuntu/jammy64"
    lab5.vm.hostname = "lab5-vm"
    lab5.vm.network "public_network"
	  lab5.vm.network "forwarded_port", guest: 7271, host: 7271
    lab5.vm.network "forwarded_port", guest: 5252, host: 5252
    lab5.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
    end

    # Synced folder for Linux VM
    lab5.vm.synced_folder ".", "/home/vagrant/project"

    # Provisioning .NET Core 8.0 installation on Ubuntu
    lab5.vm.provision "shell", run: "always", inline: <<-SHELL
      # Update the system
      sudo apt-get update
      sudo apt-get install -y wget apt-transport-https

      # Install the Microsoft GPG key
      wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb

      # Install .NET SDK
      sudo apt-get update
      sudo apt-get install -y dotnet-sdk-8.0

      # Встановлюємо .NET Runtime
      sudo apt-get install -y dotnet-runtime-8.0

      # Check the installation
      echo "Verify that .NET Core 8 is installed..."
      dotnet --version
      dotnet --list-sdks
      dotnet --list-runtimes

      if command -v dotnet &> /dev/null; then
        echo "Trying to go to project folder..."
        echo "========================================================================="
        cd /home/vagrant/project
        cd /home/vagrant/project
        echo "Available directories after first cd:"
        ls -d */ 
        cd Lab5
        
        # Шукаємо процес dotnet, що працює
        echo "Stopping the running dotnet process..."
        echo "========================================================================="

        # Знаходимо процес, що використовує порт, на якому запущений проект
        pid=$(lsof -t -i:7271)

        # Якщо процес знайдений, то його зупиняємо
        if [ -n "$pid" ]; then
          echo "Found dotnet process with PID: $pid. Stopping it..."
          kill -9 $pid
        else
          echo "No dotnet process found running on port 7271."
        fi

        dotnet dev-certs https

        echo "Trying to launch project..."
        echo "========================================================================="
        dotnet run --urls "https://0.0.0.0:7271"
        #dotnet run --urls "http://0.0.0.0:5252"
      else
        echo "Cannot start project, .NET Core 8 is not installed!"
      fi
    SHELL
  end
end


